name: fancytrains
version: '1.1'
main: me.bambam250.fancytrains.Fancytrains
api-version: '1.21'

commands:
  station:
    description: Manage train stations
    usage: /station <list|create|remove|settrain|connect|disconnect|lines|addline>
    permission: fancytrains.admin
    aliases: [st, stations]

permissions:
  fancytrains.admin:
    description: Allows management of train stations
    default: op
  fancytrains.use:
    description: Allows using train stations
    default: true